# Generated by Django 3.1.13 on 2022-10-31 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="role_name",
            field=models.CharField(choices=[("caregiver", "Caregiver")], max_length=30),
        ),
    ]
