# Generated by Django 3.0.7 on 2020-10-09 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_prize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prize',
            name='user',
        ),
        migrations.AddField(
            model_name='prize',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prize',
            name='value',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
