# Generated by Django 3.0.7 on 2021-09-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210130_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='caregivers',
            field=models.ManyToManyField(to='users.Caregiver'),
        ),
    ]
