# Generated by Django 3.1.12 on 2021-09-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_student_caregivers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='caregivers',
            field=models.ManyToManyField(related_name='students', to='users.Caregiver'),
        ),
    ]
