services:
  db:
    extends:
      file: ../docker-compose.base.yml
      service: db

  web:
    extends:
      file: ../docker-compose.base.yml
      service: web
    build: .

  migration:
    extends:
      file: ../docker-compose.base.yml
      service: migration
    build: .

volumes:
  postgres_data:

networks:
  db: