version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:27.1.2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              docker-compose \
              ruff
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app-web.tar
            - /caches/app-migration.tar
      - run:
          name: Load Docker images layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app-web.tar | true
            docker load -i /caches/app-migration.tar | true
      - run:
          name: Build application Docker images
          command: |
            docker compose build
      - run:
          name: Save Docker images layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app-web.tar app-web
            docker save -o /caches/app-migration.tar app-migration
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app-web.tar
            - /caches/app-migration.tar
      - run:
          name: Run static analysis
          command: |
            ruff check
            ruff format
      - run:
          name: Run tests
          command: |
            docker compose up --wait
            docker compose exec web pytest
      - run:
          name: Test environment clean-up
          command: |
            docker compose down
          when: always
